# https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
name: Upload Python Package

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/spider-admin-pro

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          repository: 'mouday/spider-admin-pro'
          ref: 'v3.0'
          path: 'spider_admin_pro'

      # 拉取web前端dist的代码
      - name: Checkout Web Dist
        uses: actions/checkout@v4
        with:
          repository: 'mouday/spider-admin-pro-web'
          ref: 'master'
          token: ${{ secrets.GH_PAT }}
          path: 'spider_admin_pro_web'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Build Web
        run: |
          cd spider_admin_pro_web
          pnpm install --no-frozen-lockfile
          pnpm run build:prod
          mkdir -p ../spider_admin_pro/spider_admin_pro/public
          cp -r ./dist/* ../spider_admin_pro/spider_admin_pro/public/

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd spider_admin_pro
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel --python-tag py2.py3
          twine check dist/*

      # Publishing with a Trusted Publisher
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      # https://github.com/pypa/gh-action-pypi-publish/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: spider_admin_pro/dist/
